name: Market Drop Detector

on:
  schedule:
    # Morning check (10:30 AM ET / 14:30 UTC)
    - cron: '30 14 * * 1-5'
    # Midday check (2:00 PM ET / 18:00 UTC)
    - cron: '0 18 * * 1-5'
    # End of day check (4:30 PM ET / 20:30 UTC)
    - cron: '30 20 * * 1-5'

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install yfinance requests numpy pandas

      - name: Run market drop detector
        env:
          PUSHOVER_USER:   ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN:  ${{ secrets.PUSHOVER_TOKEN }}
        run: python price_alert_bot.py