name: Earnings Release Alert

on:
  schedule:
    # Runs at 8:00 AM PT every day
    - cron: '0 15 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  alert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance requests
        
    - name: Run earnings alert bot
      env:
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
      run: python earnings_release_alert_bot.py 